# GCP Cloud Build - build and deploy API to Cloud Run, optionally deploy frontend to Firebase Hosting
# Usage: gcloud builds submit --config=cloudbuild.yaml
# Set _API_SERVICE_NAME, _REGION, _FRONTEND_APP (Firebase app) as needed via substitutions.
substitutions:
  _API_SERVICE_NAME: porygon-meal-planner-api
  _REGION: us-central1
  _FRONTEND_APP: default

steps:
  # Build backend image and push to Artifact Registry (context: server/)
  - name: 'gcr.io/cloud-builders/docker'
    id: build-api
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_API_SERVICE_NAME}:${SHORT_SHA}'
      - '-f'
      - 'server/Dockerfile'
      - 'server'

  - name: 'gcr.io/cloud-builders/docker'
    id: push-api
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_API_SERVICE_NAME}:${SHORT_SHA}'
    waitFor: ['build-api']

  # Deploy to Cloud Run (requires Cloud Run Admin, and secrets/DB configured)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: deploy-api
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_API_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_API_SERVICE_NAME}:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    waitFor: ['push-api']

options:
  logging: CLOUD_LOGGING_ONLY
